title: Melissa Cota
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9854994
  brandStrength: 0.5300752
  lightness: 0.8899033
  brandColors:
    - '#EA9B74'
    - '#28436D'
    - '#FFFFFF'
    - '#0D5DE0'
    - '#913838'
  rhythmicContrast: 0.4688507
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Melissa Cota
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4183673
layout_spectrum: 0.802466528955847
